### ISSUE TITLE
Unable to get it working

### ISSUE THREAD

**Issue by jhjacobs81** [nim65s/matrix-webhook#168]
Hello,

I have created a docker-compose.yml file like so:
```
services:
  matrix-whook:
    image: nim65s/matrix-webhook:latest
    container_name: matrix-whook
    environment:
      - MATRIX_URL="HOMESERVER"
      - MATRIX_ID="bot:HOMESERVER"
      - MATRIX_PW="PASSWORD"
      - API_KEY="SECRET"
    ports:
      - 4785:4785
    restart: always
    networks:
      - matrix-lan

networks:
    default:
        driver: bridge
    matrix-lan:
        external: true
```

This seems to spin up normally, but after that nothing happens. I can see its running when i do docker ps. But i cant invite the bot to any rooms, and when i try to use the curl command as per documentation, it just hangs.. nothing happens?

I am unsure what i am doing wrong here?
